doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     "%kernel.root_dir%/test.db3"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                type: yml
                dir: "%kernel.root_dir%/Resources/config/doctrine/App"
                is_bundle: false
                prefix: "App\\Entity"
                alias: App