framework:
    secret: '%env(APP_SECRET)%'
    annotations:
        enabled: true
        debug: true
    serializer:
        enabled: true
        enable_annotations: true
    php_errors:
        log: true
