# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    App\Importer\NewscoopApiImporter:
        public: true
        arguments:
            $client: '@GuzzleHttp\ClientInterface'
            $serializer: '@jms_serializer'

    App\Importer\NewscoopImageApiImporter:
        public: true
        arguments:
            $client: '@GuzzleHttp\ClientInterface'
            $serializer: '@jms_serializer'

    App\Publisher\TwigHtmlPublisher:
        public: true
        arguments:
            $twig: '@twig'
            $projectDir: '%kernel.project_dir%'

    App\Publisher\NinjsJsonPublisher:
        public: true
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Factory\NinjsFactory:
        public: true
        arguments:
            $publicDirPath: '%kernel.project_dir%/public'

    App\Factory\Brasil247NinjsFactory:
        public: true
        arguments:
            $publicDirPath: '%kernel.project_dir%/public'

    App\Consumer\NewscoopImportConsumer:
        public: true
        arguments:



    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Factory,Importer,Publisher,Consumer}'

    App\Serializer\SerializerInterface: '@App\Serializer\NinjsSerializer'
    App\Factory\FactoryInterface: '@App\Factory\NinjsFactory'